

% This file contains soil-related facts for Cereal crops. 
% It includes various combinations of soil conditions such as 

%	- soil type
%	- pH level
%	- nitrogen
%	- phosphorous
%	- potassium
%	- organic matter
%	- soil moisture
%	- electrical conductivity

% All suited for Cereal growth.
% soil(CropType, SoilType, PhLevel, Nitrogen, Phosphorous, Pottassium, OrganicMatter, SoilMoisture, ElectricalConductivity).


impractical_soil(_, _, _, low, low, low, low, _, _).  % Insufficient nutrients and organic matter
impractical_soil(_, _, _, high;veryHigh, _, _, _, low, _).  % Excessive nitrogen + low soil moisture
impractical_soil(_, _, _, _, _, _, low;moderate, _, high;veryHigh;extreme).  % Poor organic matter + high electrical conductivity
impractical_soil(_, _, _, _, _, _, _, high;veryHigh, low).  % High soil moisture + low electrical conductivity
impractical_soil(_, _, _, _, _, _, _, _, extreme).  % Unknown or extreme electrical conductivity
impractical_soil(_, clay, acidic;slightlyAcidic, _, _, _, _, _, _).  % Low pH in clay soil
impractical_soil(_, sandy, alkaline;slightlyAlkaline, _, _, _, _, _, _).  % High pH in sandy soil

soil_cereal(cereal, loamy, acidic, low, low, low, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, low, low, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, low, low, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, low, low, high, low, low).
soil_cereal(cereal, loamy, acidic, low, low, low, high, low, moderate).
soil_cereal(cereal, loamy, acidic, low, low, low, high, low, high).
soil_cereal(cereal, loamy, acidic, low, low, low, high, moderate, low).
soil_cereal(cereal, loamy, acidic, low, low, low, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, low, low, high, moderate, high).
soil_cereal(cereal, loamy, acidic, low, low, moderate, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, low, moderate, high, low, low).
soil_cereal(cereal, loamy, acidic, low, low, moderate, high, low, moderate).
soil_cereal(cereal, loamy, acidic, low, low, moderate, high, low, high).
soil_cereal(cereal, loamy, acidic, low, low, moderate, high, moderate, low).
soil_cereal(cereal, loamy, acidic, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, low, moderate, high, moderate, high).
soil_cereal(cereal, loamy, acidic, low, low, high, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, low, high, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, low, high, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, low, high, high, low, low).
soil_cereal(cereal, loamy, acidic, low, low, high, high, low, moderate).
soil_cereal(cereal, loamy, acidic, low, low, high, high, low, high).
soil_cereal(cereal, loamy, acidic, low, low, high, high, moderate, low).
soil_cereal(cereal, loamy, acidic, low, low, high, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, low, high, high, moderate, high).
soil_cereal(cereal, loamy, acidic, low, moderate, low, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, moderate, high, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, low, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, high, low, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, high, low, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, low, high, low, low).
soil_cereal(cereal, loamy, acidic, low, high, low, high, low, moderate).
soil_cereal(cereal, loamy, acidic, low, high, low, high, low, high).
soil_cereal(cereal, loamy, acidic, low, high, low, high, moderate, low).
soil_cereal(cereal, loamy, acidic, low, high, low, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, low, high, moderate, high).
soil_cereal(cereal, loamy, acidic, low, high, moderate, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, moderate, high, low, low).
soil_cereal(cereal, loamy, acidic, low, high, moderate, high, low, moderate).
soil_cereal(cereal, loamy, acidic, low, high, moderate, high, low, high).
soil_cereal(cereal, loamy, acidic, low, high, moderate, high, moderate, low).
soil_cereal(cereal, loamy, acidic, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, moderate, high, moderate, high).
soil_cereal(cereal, loamy, acidic, low, high, high, moderate, low, low).
soil_cereal(cereal, loamy, acidic, low, high, high, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, low, high, high, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, high, high, low, low).
soil_cereal(cereal, loamy, acidic, low, high, high, high, low, moderate).
soil_cereal(cereal, loamy, acidic, low, high, high, high, low, high).
soil_cereal(cereal, loamy, acidic, low, high, high, high, moderate, low).
soil_cereal(cereal, loamy, acidic, low, high, high, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, low, high, high, high, moderate, high).
soil_cereal(cereal, loamy, acidic, moderate, low, low, moderate, low, low).
soil_cereal(cereal, loamy, acidic, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, low, high, low, low).
soil_cereal(cereal, loamy, acidic, moderate, low, low, high, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, low, high, low, high).
soil_cereal(cereal, loamy, acidic, moderate, low, low, high, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, low, high, moderate, high).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, high, low, low).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, high, low, high).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, loamy, acidic, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, loamy, acidic, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, loamy, acidic, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, low, moderate, low, low).
soil_cereal(cereal, loamy, acidic, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, low, high, low, low).
soil_cereal(cereal, loamy, acidic, moderate, high, low, high, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, low, high, low, high).
soil_cereal(cereal, loamy, acidic, moderate, high, low, high, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, low, high, moderate, high).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, high, low, low).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, high, low, high).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, acidic, moderate, high, moderate, high, moderate, high).
soil_cereal(cereal, loamy, neutral, low, low, low, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, low, low, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, low, low, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, low, low, high, low, low).
soil_cereal(cereal, loamy, neutral, low, low, low, high, low, moderate).
soil_cereal(cereal, loamy, neutral, low, low, low, high, low, high).
soil_cereal(cereal, loamy, neutral, low, low, low, high, moderate, low).
soil_cereal(cereal, loamy, neutral, low, low, low, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, low, low, high, moderate, high).
soil_cereal(cereal, loamy, neutral, low, low, moderate, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, low, moderate, high, low, low).
soil_cereal(cereal, loamy, neutral, low, low, moderate, high, low, moderate).
soil_cereal(cereal, loamy, neutral, low, low, moderate, high, low, high).
soil_cereal(cereal, loamy, neutral, low, low, moderate, high, moderate, low).
soil_cereal(cereal, loamy, neutral, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, low, moderate, high, moderate, high).
soil_cereal(cereal, loamy, neutral, low, low, high, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, low, high, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, low, high, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, low, high, high, low, low).
soil_cereal(cereal, loamy, neutral, low, low, high, high, low, moderate).
soil_cereal(cereal, loamy, neutral, low, low, high, high, low, high).
soil_cereal(cereal, loamy, neutral, low, low, high, high, moderate, low).
soil_cereal(cereal, loamy, neutral, low, low, high, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, low, high, high, moderate, high).
soil_cereal(cereal, loamy, neutral, low, moderate, low, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, moderate, high, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, low, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, high, low, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, high, low, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, low, high, low, low).
soil_cereal(cereal, loamy, neutral, low, high, low, high, low, moderate).
soil_cereal(cereal, loamy, neutral, low, high, low, high, low, high).
soil_cereal(cereal, loamy, neutral, low, high, low, high, moderate, low).
soil_cereal(cereal, loamy, neutral, low, high, low, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, low, high, moderate, high).
soil_cereal(cereal, loamy, neutral, low, high, moderate, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, moderate, high, low, low).
soil_cereal(cereal, loamy, neutral, low, high, moderate, high, low, moderate).
soil_cereal(cereal, loamy, neutral, low, high, moderate, high, low, high).
soil_cereal(cereal, loamy, neutral, low, high, moderate, high, moderate, low).
soil_cereal(cereal, loamy, neutral, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, moderate, high, moderate, high).
soil_cereal(cereal, loamy, neutral, low, high, high, moderate, low, low).
soil_cereal(cereal, loamy, neutral, low, high, high, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, low, high, high, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, high, high, low, low).
soil_cereal(cereal, loamy, neutral, low, high, high, high, low, moderate).
soil_cereal(cereal, loamy, neutral, low, high, high, high, low, high).
soil_cereal(cereal, loamy, neutral, low, high, high, high, moderate, low).
soil_cereal(cereal, loamy, neutral, low, high, high, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, low, high, high, high, moderate, high).
soil_cereal(cereal, loamy, neutral, moderate, low, low, moderate, low, low).
soil_cereal(cereal, loamy, neutral, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, low, high, low, low).
soil_cereal(cereal, loamy, neutral, moderate, low, low, high, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, low, high, low, high).
soil_cereal(cereal, loamy, neutral, moderate, low, low, high, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, low, high, moderate, high).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, high, low, low).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, high, low, high).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, loamy, neutral, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, loamy, neutral, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, loamy, neutral, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, low, moderate, low, low).
soil_cereal(cereal, loamy, neutral, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, low, high, low, low).
soil_cereal(cereal, loamy, neutral, moderate, high, low, high, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, low, high, low, high).
soil_cereal(cereal, loamy, neutral, moderate, high, low, high, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, low, high, moderate, high).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, high, low, low).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, high, low, high).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, neutral, moderate, high, moderate, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, low, low, low, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, low, low, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, low, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, low, high, low, low).
soil_cereal(cereal, loamy, alkaline, low, low, low, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, low, high, low, high).
soil_cereal(cereal, loamy, alkaline, low, low, low, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, low, low, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, low, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, high, low, low).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, high, low, high).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, moderate, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, low, low, high, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, low, high, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, high, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, high, high, low, low).
soil_cereal(cereal, loamy, alkaline, low, low, high, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, high, high, low, high).
soil_cereal(cereal, loamy, alkaline, low, low, high, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, low, high, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, low, high, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, low, moderate, low, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, moderate, high, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, low, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, high, low, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, low, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, low, high, low, low).
soil_cereal(cereal, loamy, alkaline, low, high, low, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, low, high, low, high).
soil_cereal(cereal, loamy, alkaline, low, high, low, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, high, low, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, low, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, high, low, low).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, high, low, high).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, moderate, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, low, high, high, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, low, high, high, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, high, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, high, high, low, low).
soil_cereal(cereal, loamy, alkaline, low, high, high, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, high, high, low, high).
soil_cereal(cereal, loamy, alkaline, low, high, high, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, low, high, high, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, low, high, high, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, high, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, high, low, high).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, low, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, high, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, high, low, high).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, high, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, high, low, high).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, low, high, moderate, high).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, high, low, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, high, low, high).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, loamy, alkaline, moderate, high, moderate, high, moderate, high).
soil_cereal(cereal, clay, neutral, low, low, low, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, low, low, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, low, low, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, low, low, high, low, low).
soil_cereal(cereal, clay, neutral, low, low, low, high, low, moderate).
soil_cereal(cereal, clay, neutral, low, low, low, high, low, high).
soil_cereal(cereal, clay, neutral, low, low, low, high, moderate, low).
soil_cereal(cereal, clay, neutral, low, low, low, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, low, low, high, moderate, high).
soil_cereal(cereal, clay, neutral, low, low, moderate, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, low, moderate, high, low, low).
soil_cereal(cereal, clay, neutral, low, low, moderate, high, low, moderate).
soil_cereal(cereal, clay, neutral, low, low, moderate, high, low, high).
soil_cereal(cereal, clay, neutral, low, low, moderate, high, moderate, low).
soil_cereal(cereal, clay, neutral, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, low, moderate, high, moderate, high).
soil_cereal(cereal, clay, neutral, low, low, high, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, low, high, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, low, high, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, low, high, high, low, low).
soil_cereal(cereal, clay, neutral, low, low, high, high, low, moderate).
soil_cereal(cereal, clay, neutral, low, low, high, high, low, high).
soil_cereal(cereal, clay, neutral, low, low, high, high, moderate, low).
soil_cereal(cereal, clay, neutral, low, low, high, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, low, high, high, moderate, high).
soil_cereal(cereal, clay, neutral, low, moderate, low, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, moderate, high, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, low, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, high, low, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, high, low, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, low, high, low, low).
soil_cereal(cereal, clay, neutral, low, high, low, high, low, moderate).
soil_cereal(cereal, clay, neutral, low, high, low, high, low, high).
soil_cereal(cereal, clay, neutral, low, high, low, high, moderate, low).
soil_cereal(cereal, clay, neutral, low, high, low, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, low, high, moderate, high).
soil_cereal(cereal, clay, neutral, low, high, moderate, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, moderate, high, low, low).
soil_cereal(cereal, clay, neutral, low, high, moderate, high, low, moderate).
soil_cereal(cereal, clay, neutral, low, high, moderate, high, low, high).
soil_cereal(cereal, clay, neutral, low, high, moderate, high, moderate, low).
soil_cereal(cereal, clay, neutral, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, moderate, high, moderate, high).
soil_cereal(cereal, clay, neutral, low, high, high, moderate, low, low).
soil_cereal(cereal, clay, neutral, low, high, high, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, low, high, high, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, high, high, low, low).
soil_cereal(cereal, clay, neutral, low, high, high, high, low, moderate).
soil_cereal(cereal, clay, neutral, low, high, high, high, low, high).
soil_cereal(cereal, clay, neutral, low, high, high, high, moderate, low).
soil_cereal(cereal, clay, neutral, low, high, high, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, low, high, high, high, moderate, high).
soil_cereal(cereal, clay, neutral, moderate, low, low, moderate, low, low).
soil_cereal(cereal, clay, neutral, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, low, high, low, low).
soil_cereal(cereal, clay, neutral, moderate, low, low, high, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, low, high, low, high).
soil_cereal(cereal, clay, neutral, moderate, low, low, high, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, low, high, moderate, high).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, high, low, low).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, high, low, high).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, clay, neutral, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, clay, neutral, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, clay, neutral, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, low, moderate, low, low).
soil_cereal(cereal, clay, neutral, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, low, high, low, low).
soil_cereal(cereal, clay, neutral, moderate, high, low, high, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, low, high, low, high).
soil_cereal(cereal, clay, neutral, moderate, high, low, high, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, low, high, moderate, high).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, high, low, low).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, high, low, high).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, neutral, moderate, high, moderate, high, moderate, high).
soil_cereal(cereal, clay, alkaline, low, low, low, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, low, low, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, low, low, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, low, low, high, low, low).
soil_cereal(cereal, clay, alkaline, low, low, low, high, low, moderate).
soil_cereal(cereal, clay, alkaline, low, low, low, high, low, high).
soil_cereal(cereal, clay, alkaline, low, low, low, high, moderate, low).
soil_cereal(cereal, clay, alkaline, low, low, low, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, low, low, high, moderate, high).
soil_cereal(cereal, clay, alkaline, low, low, moderate, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, low, moderate, high, low, low).
soil_cereal(cereal, clay, alkaline, low, low, moderate, high, low, moderate).
soil_cereal(cereal, clay, alkaline, low, low, moderate, high, low, high).
soil_cereal(cereal, clay, alkaline, low, low, moderate, high, moderate, low).
soil_cereal(cereal, clay, alkaline, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, low, moderate, high, moderate, high).
soil_cereal(cereal, clay, alkaline, low, low, high, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, low, high, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, low, high, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, low, high, high, low, low).
soil_cereal(cereal, clay, alkaline, low, low, high, high, low, moderate).
soil_cereal(cereal, clay, alkaline, low, low, high, high, low, high).
soil_cereal(cereal, clay, alkaline, low, low, high, high, moderate, low).
soil_cereal(cereal, clay, alkaline, low, low, high, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, low, high, high, moderate, high).
soil_cereal(cereal, clay, alkaline, low, moderate, low, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, moderate, high, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, low, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, high, low, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, high, low, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, low, high, low, low).
soil_cereal(cereal, clay, alkaline, low, high, low, high, low, moderate).
soil_cereal(cereal, clay, alkaline, low, high, low, high, low, high).
soil_cereal(cereal, clay, alkaline, low, high, low, high, moderate, low).
soil_cereal(cereal, clay, alkaline, low, high, low, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, low, high, moderate, high).
soil_cereal(cereal, clay, alkaline, low, high, moderate, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, moderate, high, low, low).
soil_cereal(cereal, clay, alkaline, low, high, moderate, high, low, moderate).
soil_cereal(cereal, clay, alkaline, low, high, moderate, high, low, high).
soil_cereal(cereal, clay, alkaline, low, high, moderate, high, moderate, low).
soil_cereal(cereal, clay, alkaline, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, moderate, high, moderate, high).
soil_cereal(cereal, clay, alkaline, low, high, high, moderate, low, low).
soil_cereal(cereal, clay, alkaline, low, high, high, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, low, high, high, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, high, high, low, low).
soil_cereal(cereal, clay, alkaline, low, high, high, high, low, moderate).
soil_cereal(cereal, clay, alkaline, low, high, high, high, low, high).
soil_cereal(cereal, clay, alkaline, low, high, high, high, moderate, low).
soil_cereal(cereal, clay, alkaline, low, high, high, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, low, high, high, high, moderate, high).
soil_cereal(cereal, clay, alkaline, moderate, low, low, moderate, low, low).
soil_cereal(cereal, clay, alkaline, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, low, high, low, low).
soil_cereal(cereal, clay, alkaline, moderate, low, low, high, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, low, high, low, high).
soil_cereal(cereal, clay, alkaline, moderate, low, low, high, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, low, high, moderate, high).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, high, low, low).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, high, low, high).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, clay, alkaline, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, clay, alkaline, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, clay, alkaline, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, low, moderate, low, low).
soil_cereal(cereal, clay, alkaline, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, low, high, low, low).
soil_cereal(cereal, clay, alkaline, moderate, high, low, high, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, low, high, low, high).
soil_cereal(cereal, clay, alkaline, moderate, high, low, high, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, low, high, moderate, high).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, high, low, low).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, high, low, high).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, clay, alkaline, moderate, high, moderate, high, moderate, high).
soil_cereal(cereal, sandy, acidic, low, low, low, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, low, low, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, low, low, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, low, low, high, low, low).
soil_cereal(cereal, sandy, acidic, low, low, low, high, low, moderate).
soil_cereal(cereal, sandy, acidic, low, low, low, high, low, high).
soil_cereal(cereal, sandy, acidic, low, low, low, high, moderate, low).
soil_cereal(cereal, sandy, acidic, low, low, low, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, low, low, high, moderate, high).
soil_cereal(cereal, sandy, acidic, low, low, moderate, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, low, moderate, high, low, low).
soil_cereal(cereal, sandy, acidic, low, low, moderate, high, low, moderate).
soil_cereal(cereal, sandy, acidic, low, low, moderate, high, low, high).
soil_cereal(cereal, sandy, acidic, low, low, moderate, high, moderate, low).
soil_cereal(cereal, sandy, acidic, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, low, moderate, high, moderate, high).
soil_cereal(cereal, sandy, acidic, low, low, high, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, low, high, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, low, high, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, low, high, high, low, low).
soil_cereal(cereal, sandy, acidic, low, low, high, high, low, moderate).
soil_cereal(cereal, sandy, acidic, low, low, high, high, low, high).
soil_cereal(cereal, sandy, acidic, low, low, high, high, moderate, low).
soil_cereal(cereal, sandy, acidic, low, low, high, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, low, high, high, moderate, high).
soil_cereal(cereal, sandy, acidic, low, moderate, low, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, moderate, high, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, low, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, high, low, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, high, low, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, low, high, low, low).
soil_cereal(cereal, sandy, acidic, low, high, low, high, low, moderate).
soil_cereal(cereal, sandy, acidic, low, high, low, high, low, high).
soil_cereal(cereal, sandy, acidic, low, high, low, high, moderate, low).
soil_cereal(cereal, sandy, acidic, low, high, low, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, low, high, moderate, high).
soil_cereal(cereal, sandy, acidic, low, high, moderate, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, moderate, high, low, low).
soil_cereal(cereal, sandy, acidic, low, high, moderate, high, low, moderate).
soil_cereal(cereal, sandy, acidic, low, high, moderate, high, low, high).
soil_cereal(cereal, sandy, acidic, low, high, moderate, high, moderate, low).
soil_cereal(cereal, sandy, acidic, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, moderate, high, moderate, high).
soil_cereal(cereal, sandy, acidic, low, high, high, moderate, low, low).
soil_cereal(cereal, sandy, acidic, low, high, high, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, low, high, high, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, high, high, low, low).
soil_cereal(cereal, sandy, acidic, low, high, high, high, low, moderate).
soil_cereal(cereal, sandy, acidic, low, high, high, high, low, high).
soil_cereal(cereal, sandy, acidic, low, high, high, high, moderate, low).
soil_cereal(cereal, sandy, acidic, low, high, high, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, low, high, high, high, moderate, high).
soil_cereal(cereal, sandy, acidic, moderate, low, low, moderate, low, low).
soil_cereal(cereal, sandy, acidic, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, low, high, low, low).
soil_cereal(cereal, sandy, acidic, moderate, low, low, high, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, low, high, low, high).
soil_cereal(cereal, sandy, acidic, moderate, low, low, high, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, low, high, moderate, high).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, high, low, low).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, high, low, high).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, sandy, acidic, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, sandy, acidic, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, sandy, acidic, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, low, moderate, low, low).
soil_cereal(cereal, sandy, acidic, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, low, high, low, low).
soil_cereal(cereal, sandy, acidic, moderate, high, low, high, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, low, high, low, high).
soil_cereal(cereal, sandy, acidic, moderate, high, low, high, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, low, high, moderate, high).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, high, low, low).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, high, low, high).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, acidic, moderate, high, moderate, high, moderate, high).
soil_cereal(cereal, sandy, neutral, low, low, low, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, low, low, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, low, low, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, low, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, low, low, high, low, low).
soil_cereal(cereal, sandy, neutral, low, low, low, high, low, moderate).
soil_cereal(cereal, sandy, neutral, low, low, low, high, low, high).
soil_cereal(cereal, sandy, neutral, low, low, low, high, moderate, low).
soil_cereal(cereal, sandy, neutral, low, low, low, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, low, low, high, moderate, high).
soil_cereal(cereal, sandy, neutral, low, low, moderate, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, low, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, low, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, low, moderate, high, low, low).
soil_cereal(cereal, sandy, neutral, low, low, moderate, high, low, moderate).
soil_cereal(cereal, sandy, neutral, low, low, moderate, high, low, high).
soil_cereal(cereal, sandy, neutral, low, low, moderate, high, moderate, low).
soil_cereal(cereal, sandy, neutral, low, low, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, low, moderate, high, moderate, high).
soil_cereal(cereal, sandy, neutral, low, low, high, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, low, high, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, low, high, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, low, high, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, low, high, high, low, low).
soil_cereal(cereal, sandy, neutral, low, low, high, high, low, moderate).
soil_cereal(cereal, sandy, neutral, low, low, high, high, low, high).
soil_cereal(cereal, sandy, neutral, low, low, high, high, moderate, low).
soil_cereal(cereal, sandy, neutral, low, low, high, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, low, high, high, moderate, high).
soil_cereal(cereal, sandy, neutral, low, moderate, low, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, moderate, low, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, moderate, low, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, moderate, moderate, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, moderate, high, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, moderate, high, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, moderate, high, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, moderate, high, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, low, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, high, low, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, high, low, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, high, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, low, high, low, low).
soil_cereal(cereal, sandy, neutral, low, high, low, high, low, moderate).
soil_cereal(cereal, sandy, neutral, low, high, low, high, low, high).
soil_cereal(cereal, sandy, neutral, low, high, low, high, moderate, low).
soil_cereal(cereal, sandy, neutral, low, high, low, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, low, high, moderate, high).
soil_cereal(cereal, sandy, neutral, low, high, moderate, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, high, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, high, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, moderate, high, low, low).
soil_cereal(cereal, sandy, neutral, low, high, moderate, high, low, moderate).
soil_cereal(cereal, sandy, neutral, low, high, moderate, high, low, high).
soil_cereal(cereal, sandy, neutral, low, high, moderate, high, moderate, low).
soil_cereal(cereal, sandy, neutral, low, high, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, moderate, high, moderate, high).
soil_cereal(cereal, sandy, neutral, low, high, high, moderate, low, low).
soil_cereal(cereal, sandy, neutral, low, high, high, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, low, high, high, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, low, high, high, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, high, high, low, low).
soil_cereal(cereal, sandy, neutral, low, high, high, high, low, moderate).
soil_cereal(cereal, sandy, neutral, low, high, high, high, low, high).
soil_cereal(cereal, sandy, neutral, low, high, high, high, moderate, low).
soil_cereal(cereal, sandy, neutral, low, high, high, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, low, high, high, high, moderate, high).
soil_cereal(cereal, sandy, neutral, moderate, low, low, moderate, low, low).
soil_cereal(cereal, sandy, neutral, moderate, low, low, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, low, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, low, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, low, high, low, low).
soil_cereal(cereal, sandy, neutral, moderate, low, low, high, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, low, high, low, high).
soil_cereal(cereal, sandy, neutral, moderate, low, low, high, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, low, low, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, low, high, moderate, high).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, moderate, low, low).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, high, low, low).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, high, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, high, low, high).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, high, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, low, moderate, high, moderate, high).
soil_cereal(cereal, sandy, neutral, moderate, moderate, low, moderate, low, low).
soil_cereal(cereal, sandy, neutral, moderate, moderate, low, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, moderate, low, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, moderate, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, moderate, moderate, moderate, low, low).
soil_cereal(cereal, sandy, neutral, moderate, moderate, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, moderate, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, moderate, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, low, moderate, low, low).
soil_cereal(cereal, sandy, neutral, moderate, high, low, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, low, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, high, low, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, low, high, low, low).
soil_cereal(cereal, sandy, neutral, moderate, high, low, high, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, low, high, low, high).
soil_cereal(cereal, sandy, neutral, moderate, high, low, high, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, high, low, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, low, high, moderate, high).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, moderate, low, low).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, moderate, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, moderate, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, moderate, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, high, low, low).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, high, low, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, high, low, high).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, high, moderate, low).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, high, moderate, moderate).
soil_cereal(cereal, sandy, neutral, moderate, high, moderate, high, moderate, high).
